export default [
  {
    title: "Banking app",
    titleLinkName: "Solera National Bank Application App",
    titleLinkHref: "https://join.solerabank.com",
    img: "solera-bank.jpg",
    imgHref: "https://join.solerabank.com",
    body: "I lead on the front-end and back-end of this new retirement account banking app.",
    technologies: [
      "React.js (client-side rendered)",
      "Node.js",
      "Express",
      "many GCP services",
    ],
  },
  {
    title: "Next.js e-commerce site",
    titleLinkName: "Bamboo Sushi",
    titleLinkHref: "https://bamboosushi.com/",
    img: "bamboo-sushi.jpg",
    imgHref: "https://bamboosushi.com/",
    body: "Built a custom cart and checkout react component utilizing Shopify's GraphQL API.",
    technologies: ["Next.js", "Shopify", "GraphQL"],
  },
  {
    title: "JAM stack website",
    titleLinkName: "Vinoshipper",
    titleLinkHref: "https://www.vinoshipper.com",
    img: "vinoshipper.jpg",
    imgHref: "https://www.vinoshipper.com/",
    body: "Lead developer on custom JAM stack website.",
    technologies: ["React.js", "Gatsby (with GraphQL)", "Styled-components"],
  },
  {
    title: "Shopify e-commerce",
    titleLinkName: "Territorial Seed",
    titleLinkHref: "https://territorialseed.com/",
    img: "territorial-seed.jpg",
    imgHref: "https://territorialseed.com/",
    body: "I joined the project after launch and developed new custom features, mainly in JavaScript.",
    technologies: ["Vanilla JavaScript"],
  },
  {
    title: "JAM stack website",
    titleLinkName: "Bay Equity Home Loans",
    titleLinkHref: "https://bayequityhomeloans.com/",
    img: "bay-equity.jpg",
    imgHref: "https://bayequityhomeloans.com/",
    body: "Helped build custom features for this JAM stack site",
    technologies: ["Gatsby", "D3.js", "Firebase"],
  },
  {
    title: "Hotel Booking System",
    titleLinkName: "Palms Casino and Resort",
    titleLinkHref: "https://www.palms.com",
    img: "palms-1.jpg",
    imgHref: "https://www.palms.com",
    img2: "palms-2.jpg",
    body: "Worked on the front-end for this new website, focusing on the booking engine.",
    technologies: ["React.js", "Redux", "custom APIs"],
    height: 2,
  },
  {
    title: "E-commerce product aggregator",
    titleLinkName: "DesignTbl",
    titleLinkHref: "https://eatoncw.github.io/designtbl_furniture/",
    img: "projects1_shot1.jpg",
    imgHref: "https://eatoncw.github.io/designtbl_furniture/",
    img2: "projects1_shot2.jpg",
    body: "Built using React.js and RoR, DesignTbl helped users find great prices on home furniture products. The back-end accesses retailer APIs + web scraping to aggregate on-sale products.",
    technologies: [
      "React",
      "Redux",
      "Rails 5 API-only",
      "APIs",
      "Redis",
      "Heroku",
    ],
    height: 2,
  },
];
