export default {
  "Front-end": [
    "JavaScript",
    "TypeScript",
    "React.js",
    "React Native",
    "Next.js",
    "Gatsby",
    "HTML5",
    "CSS3",
    "PostCSS",
    "Sass",
    "Material-UI",
    "D3.js",
  ],
  "Back-end": [
    "Node.js",
    "Express",
    "Firebase",
    "Google Cloud Platform",
    "REST APIs",
    "GraphQL",
    "Docker",
    "Heroku",
    "Redis",
    "Ruby",
    "Rails",
    "Python",
    "Rust (basic)",
  ],
};
